'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { supabase } from '@/lib/supabaseClient';
import { toast } from 'sonner';
import { Save, Eye, EyeOff, Music, Mic2, GripHorizontal, ArrowLeft, Loader2, Sparkles, BrainCircuit } from 'lucide-react';
import Link from 'next/link';
import SongViewer from '@/components/songs/SongViewer';
import { parseSongSheet } from '@/lib/songParser';

export default function AddSongPage() {
    const router = useRouter();
    const [isLoading, setIsLoading] = useState(false);
    const [showPreview, setShowPreview] = useState(false);
    const [magicText, setMagicText] = useState('');
    const [showMagic, setShowMagic] = useState(false); // Kept for legacy if needed, but UI uses activeTab now

    // AI & Tabs State
    const [activeTab, setActiveTab] = useState<'manual' | 'ai'>('manual');
    const [aiPrompt, setAiPrompt] = useState('');
    const [isGenerating, setIsGenerating] = useState(false);

    const handleAiGenerate = async () => {
        if (!aiPrompt.trim()) return;

        setIsGenerating(true);
        try {
            const res = await fetch('/api/generate-song', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ songName: aiPrompt })
            });

            const data = await res.json();

            if (!res.ok) throw new Error(data.error || 'Failed to generate');

            setFormData(prev => ({
                ...prev,
                title: data.title || prev.title,
                artist: data.artist || prev.artist,
                key: data.key || prev.key,
                tempo: data.tempo || prev.tempo,
                lyrics: data.lyrics || "",
                chords: data.chords || "",
                youtube_id: data.youtube_id || prev.youtube_id,
                img: data.img || prev.img
            }));

            toast.success("AI Generation Successful!");
        } catch (error: any) {
            console.error(error);
            toast.error(error.message || "Something went wrong with AI generation.");
        } finally {
            setIsGenerating(false);
        }
    };

    const handleMagicPaste = () => {
        if (!magicText.trim()) return;

        try {
            const { chords, lyrics, title, artist, key, tempo } = parseSongSheet(magicText);
            setFormData(prev => ({
                ...prev,
                chords: chords,
                lyrics: lyrics,
                title: title || prev.title,
                artist: artist || prev.artist,
                key: key || prev.key,
                tempo: tempo || prev.tempo
            }));

            toast.success("Magic applied! Chords and Lyrics parsed.");
            setShowMagic(false);
        } catch (error) {
            toast.error("Failed to parse. Is current format correct?");
        }
    };

    const [formData, setFormData] = useState({
        title: '',
        artist: '',
        category: 'worship',
        key: '',
        tempo: '',
        youtube_id: '',
        img: '',
        lyrics: '',
        hindi_lyrics: '',
        chords: ''
    });

    const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
        setFormData({ ...formData, [e.target.name]: e.target.value });
    };

    const generateId = (title: string) => {
        return title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)+/g, '');
    };

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        setIsLoading(true);

        // Validation
        if (!formData.title || !formData.lyrics) {
            toast.error("Title and Lyric are required!");
            setIsLoading(false);
            return;
        }

        try {
            const { error } = await supabase
                .from('songs')
                .insert([
                    {
                        // id is auto-generated by database (uuid)
                        title: formData.title,
                        artist: formData.artist,
                        category: formData.category,
                        key: formData.key,
                        tempo: formData.tempo,
                        youtube_id: formData.youtube_id,
                        img: formData.img || 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&q=80', // Default image
                        lyrics: formData.lyrics,
                        hindi_lyrics: formData.hindi_lyrics || null,
                        chords: formData.chords || null,
                        created_by: (await supabase.auth.getUser()).data.user?.id
                    }
                ]);

            if (error) throw error;

            toast.success("Song added successfully! 🎉");
            router.push('/admin/songs'); // Or verify by going to the song page
        } catch (error: any) {
            console.error('Error adding song:', error);
            toast.error(error.message || "Failed to add song.");
        } finally {
            setIsLoading(false);
        }
    };

    return (
        <div className="max-w-7xl mx-auto pb-20">
            {/* Header */}
            <div className="flex items-center justify-between mb-8">
                <div className="flex items-center gap-4">
                    <Link href="/admin" className="p-2 rounded-full hover:bg-white/10 text-white/50 hover:text-white transition-colors">
                        <ArrowLeft className="w-5 h-5" />
                    </Link>
                    <h1 className="text-3xl font-black text-white tracking-tight">Add New Song</h1>
                </div>
                <button
                    type="button"
                    onClick={() => setShowPreview(!showPreview)}
                    className={`flex items-center gap-2 px-5 py-2.5 rounded-full text-xs font-bold uppercase tracking-widest transition-all ${showPreview
                        ? 'bg-[var(--brand)] text-white shadow-lg shadow-[var(--brand)]/20'
                        : 'bg-white/10 text-white hover:bg-white/20'
                        }`}
                >
                    {showPreview ? <><EyeOff className="w-4 h-4" /> Edit Mode</> : <><Eye className="w-4 h-4" /> Preview Mode</>}
                </button>
            </div>

            {showPreview ? (
                // PREVIEW MODE
                <div className="rounded-3xl overflow-hidden border border-white/10 bg-[#050505]">
                    <div className="bg-amber-500/10 border-b border-amber-500/20 p-3 text-center text-amber-500 text-xs font-bold uppercase tracking-widest">
                        Live Preview (Not Saved)
                    </div>
                    <SongViewer
                        songId="preview-mode"
                        title={formData.title || "Song Title"}
                        author={formData.artist || "Artist Name"}
                        originalKey={formData.key || "C"}
                        tempo={formData.tempo}
                        lyrics={formData.lyrics || "Lyrics will appear here..."}
                        hindiLyrics={formData.hindi_lyrics}
                        chords={formData.chords}
                        youtubeId={formData.youtube_id}
                        category={formData.category}
                        relatedSongs={[]} // Empty for preview
                    />
                </div>
            ) : (
                <>
                    {/* MAGIC IMPORT */}
                    {/* IMPORT TOOLS SECTION */}
                    <div className="mb-8">
                        <div className="flex gap-4 mb-4">
                            <button
                                onClick={() => setActiveTab('manual')}
                                className={`flex items-center gap-2 text-sm font-bold uppercase tracking-widest transition-colors ${activeTab === 'manual' ? 'text-amber-500' : 'text-white/40 hover:text-white'
                                    }`}
                            >
                                <Sparkles className="w-4 h-4" />
                                Magic Paste (Manual)
                            </button>
                            <span className="text-white/10">|</span>
                            <button
                                onClick={() => setActiveTab('ai')}
                                className={`flex items-center gap-2 text-sm font-bold uppercase tracking-widest transition-colors ${activeTab === 'ai' ? 'text-amber-500' : 'text-white/40 hover:text-white'
                                    }`}
                            >
                                <BrainCircuit className="w-4 h-4" />
                                AI Auto-Generate
                            </button>
                        </div>

                        {activeTab === 'manual' && (
                            <div className="bg-gradient-to-r from-amber-500/10 to-transparent border border-amber-500/20 rounded-3xl p-6 animate-fade-in-down mb-8">
                                <h3 className="text-lg font-bold text-white mb-2">Paste Sheet Music</h3>
                                <p className="text-white/40 text-sm mb-4">
                                    Paste mixed lyrics/chords here. We'll separate them and automatically extract metadata if you provide it (e.g. "Title: Way Maker").
                                </p>
                                <textarea
                                    value={magicText}
                                    onChange={(e) => setMagicText(e.target.value)}
                                    rows={8}
                                    className="w-full bg-[#0A0A0A] border border-white/10 rounded-xl p-4 text-xs font-mono text-white/80 focus:outline-none focus:border-amber-500/50 mb-4"
                                    placeholder={`Title: Amazing Grace\nArtist: John Newton\nKey: G\n\nG        D\nAmazing Grace\n      Em      C\nHow sweet the sound`}
                                />
                                <button
                                    type="button"
                                    onClick={handleMagicPaste}
                                    className="px-6 py-3 bg-amber-500 text-black font-bold rounded-xl hover:bg-amber-400 transition-colors flex items-center gap-2 text-sm"
                                >
                                    <Sparkles className="w-4 h-4" />
                                    Auto-Process
                                </button>
                            </div>
                        )}

                        {activeTab === 'ai' && (
                            <div className="bg-gradient-to-r from-purple-500/10 to-transparent border border-purple-500/20 rounded-3xl p-6 animate-fade-in-down mb-8">
                                <h3 className="text-lg font-bold text-white mb-2">AI Auto-Generate</h3>
                                <p className="text-white/40 text-sm mb-4">
                                    Enter the song title, and our AI will fetch the lyrics, chords, key, and tempo for you.
                                </p>
                                <div className="flex gap-4">
                                    <input
                                        type="text"
                                        value={aiPrompt}
                                        onChange={(e) => setAiPrompt(e.target.value)}
                                        placeholder="e.g. Way Maker by Sinach"
                                        className="flex-1 bg-[#0A0A0A] border border-white/10 rounded-xl p-4 text-sm text-white focus:outline-none focus:border-purple-500/50"
                                    />
                                    <button
                                        type="button"
                                        onClick={handleAiGenerate}
                                        disabled={isGenerating || !aiPrompt.trim()}
                                        className="px-6 py-3 bg-purple-600 text-white font-bold rounded-xl hover:bg-purple-500 transition-colors flex items-center gap-2 text-sm disabled:opacity-50 disabled:cursor-not-allowed"
                                    >
                                        {isGenerating ? <Loader2 className="w-4 h-4 animate-spin" /> : <BrainCircuit className="w-4 h-4" />}
                                        Generate
                                    </button>
                                </div>
                                <p className="text-xs text-white/20 mt-2">* Requires OPENAI_API_KEY in server environment.</p>
                            </div>
                        )}
                    </div>

                    {/* EDIT MODE */}
                    <form onSubmit={handleSubmit} className="grid grid-cols-1 lg:grid-cols-3 gap-8">
                        {/* LEFT: Metadata */}
                        <div className="lg:col-span-1 space-y-6">
                            <section className="bg-white/5 rounded-3xl p-6 border border-white/5 space-y-4">
                                <h2 className="text-sm font-bold text-white/40 uppercase tracking-widest flex items-center gap-2 mb-4">
                                    <Music className="w-4 h-4" />
                                    Basic Info
                                </h2>

                                <Input label="Song Title" name="title" value={formData.title} onChange={handleChange} required placeholder="e.g. Way Maker" />
                                <Input label="Artist" name="artist" value={formData.artist} onChange={handleChange} placeholder="e.g. Sinach" />

                                <div>
                                    <label className="block text-xs font-bold text-white/40 uppercase tracking-widest mb-2">Category</label>
                                    <select
                                        name="category"
                                        value={formData.category}
                                        onChange={handleChange}
                                        className="w-full bg-[#0A0A0A] border border-white/10 rounded-xl px-4 py-3 text-white focus:outline-none focus:border-amber-500/50 transition-colors"
                                    >
                                        <option value="worship">Worship</option>
                                        <option value="praise">Praise</option>
                                        <option value="hymns">Hymns</option>
                                        <option value="kids">Kids</option>
                                        <option value="hindi">Hindi</option>
                                        <option value="contemporary">Contemporary</option>
                                    </select>
                                </div>
                            </section>

                            <section className="bg-white/5 rounded-3xl p-6 border border-white/5 space-y-4">
                                <h2 className="text-sm font-bold text-white/40 uppercase tracking-widest flex items-center gap-2 mb-4">
                                    <GripHorizontal className="w-4 h-4" />
                                    Details
                                </h2>

                                <div className="grid grid-cols-2 gap-4">
                                    <Input label="Key" name="key" value={formData.key} onChange={handleChange} placeholder="e.g. G" />
                                    <Input label="Tempo" name="tempo" value={formData.tempo} onChange={handleChange} placeholder="e.g. 72 BPM" />
                                </div>
                                <Input label="YouTube ID" name="youtube_id" value={formData.youtube_id} onChange={handleChange} placeholder="e.g. iJCV_2H9xD0" />
                                <Input label="Cover Image URL" name="img" value={formData.img} onChange={handleChange} placeholder="https://..." />
                            </section>

                            <button
                                type="submit"
                                disabled={isLoading}
                                className={`w-full py-4 rounded-xl font-bold text-black text-lg transition-all shadow-lg ${isLoading ? 'bg-amber-500/50 cursor-not-allowed' : 'bg-amber-500 hover:bg-amber-400 hover:scale-[1.02]'
                                    }`}
                            >
                                {isLoading ? (
                                    <span className="flex items-center justify-center gap-2"><Loader2 className="w-5 h-5 animate-spin" /> Saving...</span>
                                ) : (
                                    <span className="flex items-center justify-center gap-2"><Save className="w-5 h-5" /> Upload Song</span>
                                )}
                            </button>
                        </div>

                        {/* RIGHT: Editors */}
                        <div className="lg:col-span-2 space-y-6">
                            <section className="bg-white/5 rounded-3xl p-6 border border-white/5 h-full">
                                <h2 className="text-sm font-bold text-white/40 uppercase tracking-widest flex items-center gap-2 mb-4">
                                    <Mic2 className="w-4 h-4" />
                                    Content
                                </h2>

                                <div className="space-y-6">
                                    <div>
                                        <div className="flex justify-between mb-2">
                                            <label className="text-xs font-bold text-white/40 uppercase tracking-widest">Lyrics (English) *</label>
                                            <span className="text-xs text-white/20">Paste plain text here</span>
                                        </div>
                                        <textarea
                                            name="lyrics"
                                            value={formData.lyrics}
                                            onChange={handleChange}
                                            required
                                            rows={12}
                                            className="w-full bg-[#0A0A0A] border border-white/10 rounded-xl px-4 py-4 text-white font-serif leading-relaxed focus:outline-none focus:border-amber-500/50 transition-colors resize-none placeholder:text-white/10"
                                            placeholder={`Way maker, miracle worker...\nPromise keeper, light in the darkness...`}
                                        />
                                    </div>

                                    <div>
                                        <div className="flex justify-between mb-2">
                                            <label className="text-xs font-bold text-white/40 uppercase tracking-widest">Chords (ChordPro / Bracket Format)</label>
                                            <span className="text-xs text-white/20">Use [C] [G] [Am] format</span>
                                        </div>
                                        <textarea
                                            name="chords"
                                            value={formData.chords}
                                            onChange={handleChange}
                                            rows={10}
                                            className="w-full bg-[#0A0A0A] border border-white/10 rounded-xl px-4 py-4 text-amber-200/80 font-mono text-sm leading-relaxed focus:outline-none focus:border-amber-500/50 transition-colors resize-none placeholder:text-white/10"
                                            placeholder={`[Verse 1]\n[G]           [C]\nYou are here, moving in our midst`}
                                        />
                                    </div>

                                    <div>
                                        <div className="flex justify-between mb-2">
                                            <label className="text-xs font-bold text-white/40 uppercase tracking-widest">Hindi Lyrics (Optional)</label>
                                        </div>
                                        <textarea
                                            name="hindi_lyrics"
                                            value={formData.hindi_lyrics}
                                            onChange={handleChange}
                                            rows={6}
                                            className="w-full bg-[#0A0A0A] border border-white/10 rounded-xl px-4 py-4 text-white font-serif leading-relaxed focus:outline-none focus:border-amber-500/50 transition-colors resize-none placeholder:text-white/10"
                                            placeholder={`तू यहाँ है...\nकार्य कर रहा है...`}
                                        />
                                    </div>
                                </div>
                            </section>
                        </div>
                    </form>
                </>
            )}
        </div>
    );
}

function Input({ label, name, value, onChange, placeholder, required }: any) {
    return (
        <div>
            <label className="block text-xs font-bold text-white/40 uppercase tracking-widest mb-2">
                {label} {required && <span className="text-red-500">*</span>}
            </label>
            <input
                type="text"
                name={name}
                value={value}
                onChange={onChange}
                placeholder={placeholder}
                required={required}
                className="w-full bg-[#0A0A0A] border border-white/10 rounded-xl px-4 py-3 text-white placeholder:text-white/20 focus:outline-none focus:border-amber-500/50 transition-colors font-medium"
            />
        </div>
    );
}
